### PR TITLE
Fix deps

### PR DESCRIPTION
**Pull request by msizanoen1**

### CODE REVIEW

**Comment by msizanoen1** [comment]
@qtmlabs-homu r+

**Comment by qtmlabs-homu** [comment]
:pushpin: Commit 2ab49be5f63eb084ac767a51d2abc5aebc13ccf6 has been approved by `msizanoen1`

**Comment by qtmlabs-homu** [comment]
:hourglass: Testing commit 2ab49be5f63eb084ac767a51d2abc5aebc13ccf6 with merge 60095c2acda0c472dc3f970fae117fd05b4e4e26...

**Comment by qtmlabs-homu** [comment]
:sunny: Test successful - [checks-azure](https://dev.azure.com/qtmlabs0410/77005577-a4fb-438c-b44b-698400a4c058/_build/results?buildId=249)
Approved by: msizanoen1
Pushing 60095c2acda0c472dc3f970fae117fd05b4e4e26 to master...

**Pull request merged**
