### PR TITLE
Remove lsb

### PR DESCRIPTION
**Pull request by msizanoen1**

### CODE REVIEW

**Comment by msizanoen1** [comment]
@qtmlabs-homu r+

**Comment by qtmlabs-homu** [comment]
:pushpin: Commit 4a17a8fcb18f84e0980ec0868b9b66ace8b2fc47 has been approved by `msizanoen1`

**Comment by qtmlabs-homu** [comment]
:hourglass: Testing commit 4a17a8fcb18f84e0980ec0868b9b66ace8b2fc47 with merge 5d22788d7da1c67d3b63d0292c044c8bc0bc0b3e...

**Comment by msizanoen1** [comment]
@qtmlabs-homu r-

**Comment by qtmlabs-homu** [comment]
:sunny: Try build successful - [checks-azure](https://dev.azure.com/qtmlabs0410/77005577-a4fb-438c-b44b-698400a4c058/_build/results?buildId=246)
Build commit: 5d22788d7da1c67d3b63d0292c044c8bc0bc0b3e (`5d22788d7da1c67d3b63d0292c044c8bc0bc0b3e`)

**Pull request closed without merging**
