### PR TITLE
Delete README.md

### PR DESCRIPTION
**Pull request by msizanoen1**

### CODE REVIEW

**Comment by msizanoen1** [comment]
@qtmlabs-homu r+

**Comment by msizanoen1** [comment]
@qtmlabs-homu r+

**Comment by qtmlabs-homu** [comment]
:pushpin: Commit 016c0084f42450b6dd2a5225b1fc1b8f198f6980 has been approved by `msizanoen1`

**Comment by qtmlabs-homu** [comment]
:hourglass: Testing commit 016c0084f42450b6dd2a5225b1fc1b8f198f6980 with merge baa98dd3e89a584b951df140513073152562f00b...

**Comment by qtmlabs-homu** [comment]
:sunny: Test successful - [checks-azure](https://dev.azure.com/qtmlabs0410/77005577-a4fb-438c-b44b-698400a4c058/_build/results?buildId=252)
Approved by: msizanoen1
Pushing baa98dd3e89a584b951df140513073152562f00b to master...

**Comment by qtmlabs-homu** [comment]
Test

**Pull request merged**
